name: .NET CI

on:
  workflow_call:
    inputs:
      solution:
        description: 'Solution or project path for restore/build.'
        required: true
        type: string
      dotnet-version:
        description: '.NET SDK version.'
        required: false
        type: string
        default: '10.0'
    # secrets:
    #   GITHUB_TOKEN:
    #     required: true

permissions:
  contents: read
  packages: read

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Set up .NET and authenticate GitHub Packages
        uses: UtopikCode/github-actions/.github/actions/dotnet-setup@main
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore dependencies
        run: dotnet restore ${{ inputs.solution }}

      - name: Build solution
        run: dotnet build ${{ inputs.solution }} --configuration Release --no-restore
