name: Go CI

on:
  workflow_call:
    inputs:
      go-module:
        description: 'Go module or package path to build.'
        required: true
        type: string
      go-version:
        description: 'Go SDK version.'
        required: false
        type: string
        default: '1.22'
      go-args:
        description: 'Additional go build arguments.'
        required: false
        type: string
        default: './...'

permissions:
  contents: read

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}

      - name: Download module dependencies
        working-directory: ${{ inputs.go-module }}
        run: go mod download

      - name: Build module
        working-directory: ${{ inputs.go-module }}
        run: go build ${{ inputs.go-args }}
