name: Go CI

on:
  workflow_call:
    inputs:
      go-version:
        description: 'Go SDK version.'
        required: false
        type: string
        default: '1.23'
      make-target:
        description: 'Make target to run.'
        required: false
        type: string
        default: 'ci'
      working-directory:
        description: 'Directory to run make in.'
        required: false
        type: string
        default: '.'

permissions:
  contents: read

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}

      - name: Run full CI
        working-directory: ${{ inputs.working-directory }}
        run: make ${{ inputs.make-target }}
