name: Upload generated OpenAPI spec

on:
  workflow_call:
    inputs:
      openapi-dll:
        description: 'Compiled OpenAPI DLL path.'
        required: false
        type: string
        default: ''
      openapi-output:
        description: 'OpenAPI JSON output file path.'
        required: true
        type: string
        default: 'openapi.json'
      openapi-upload-artifact:
        description: 'Upload generated OpenAPI JSON as a workflow artifact.'
        required: false
        type: boolean
        default: true
      openapi-upload-artifact-name:
        description: 'Artifact name for the generated OpenAPI JSON file.'
        required: false
        type: string
        default: 'openapi-spec'
      openapi-temp-artifact:
        description: 'Temporary artifact name used to transfer the generated OpenAPI file between jobs.'
        required: false
        type: string
        default: 'openapi-spec-temp'

jobs:
  upload:
    if: ${{ inputs.openapi-upload-artifact && inputs.openapi-dll != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download generated OpenAPI spec artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.openapi-temp-artifact }}
          path: downloaded

      - name: Upload generated OpenAPI spec
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ inputs.openapi-upload-artifact-name }}
          path: downloaded/${{ inputs.openapi-output }}
          if-no-files-found: warn
          overwrite: true
